<?php

namespace AppBundle\Repository;

/**
 * ActividadFraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadFraseRepository extends \Doctrine\ORM\EntityRepository
{
}
