<?php

namespace AppBundle\Repository;

/**
 * AmistadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmistadRepository extends \Doctrine\ORM\EntityRepository
{

    public function misAmigos($nombre, $usuario)
    {

        $nombre = strtoupper(trim($nombre));

        $arrayNombre = explode(' ', $nombre);

        foreach ($arrayNombre as $n) {
            $arraySqlNombre [] = "p.nombre like '%$n%' OR p.apellido like '%$n%'";
        }

        $sqlNombre = implode(' OR ', $arraySqlNombre);


        $qb = $this->createQueryBuilder('amistad')
            ->innerJoin('amistad.usuarioA', 'usuarioA')
            ->innerJoin('amistad.usuarioB', 'usuarioB')
            ->innerJoin('usuarioB.persona', 'p')
            ->where('amistad.activo = true')
            ->where('usuarioB.enabled = true')
            ->andWhere($sqlNombre)
            ->andWhere('usuarioA = :usuario')
            ->setParameter('usuario', $usuario)
            ->setMaxResults(15);

        return $qb->getQuery()->getResult();;

    }
}
