<?php

namespace AppBundle\Repository;

/**
 * DocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteRepository extends \Doctrine\ORM\EntityRepository
{
}
