<?php

namespace AppBundle\Repository;

/**
 * FotoPersonaLugarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FotoPersonaLugarRepository extends \Doctrine\ORM\EntityRepository
{
}
