<?php

namespace AppBundle\Repository;

/**
 * FraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraseRepository extends \Doctrine\ORM\EntityRepository
{
}
