<?php

namespace AppBundle\Repository;

/**
 * FraseItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraseItemRepository extends \Doctrine\ORM\EntityRepository
{
}
