<?php

namespace AppBundle\Repository;

/**
 * PictogramaCustomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictogramaCustomRepository extends \Doctrine\ORM\EntityRepository
{

    public function misPictos($user)
    {
        $qb = $this->createQueryBuilder('p')
            ->andWhere("p.activo = true")
            ->andWhere("p.creadoPor = :user")
            ->setParameter("user", $user);

        return $qb->getQuery()->getResult();

    }
}
