# usuario:
#     resource: "@UsuarioBundle/Resources/config/routing.yml"
#     prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:  /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api

api_login_check:
    path: /api/login_check
    methods:  [POST]